name: Rapport COT - Update CSV Data

on:
  schedule:
    - cron: '0 6 * * 6'
  workflow_dispatch:

jobs:
  update-csv-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Dependencies Installation
        run: |
          pip install requests

      - name: Python Script Execution (with Retries)
        # On utilise cette action pour gérer les relances
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 5
          retry_wait_seconds: 300
          command: python scripts/CSV_Updater.py

      - name: Save and Push CSV Files to GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add csv/
          git diff --staged --quiet || (git commit -m "Automated Update 📈" && git push)
