name: Rapport COT - Update CSV Data

on:
  schedule:
    # Hour server is in UTC.
    # 6:00 UTC correspond to 7:00 in France (winter time) or 8:00 (summer time).
    # '6' mean Saturday.
    - cron: '0 6 * * 6'

  # We add a workflow_dispatch trigger to be able to launch the workflow manually from GitHub Actions tab.
  workflow_dispatch:

jobs:
  update-csv-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # <-- AJOUT ICI : Coupe le workflow s'il dure plus de 10 minutes

    # IMPORTANT : Give github the autorization to push on the repo
    permissions:
      contents: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Dependencies Installation
        run: |
          pip install requests

      - name: Python Script Execution
        # We run the script that is in the scripts/ folder
        run: python scripts/CSV_Updater.py

      - name: Save and Push CSV Files to GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git add csv/

          git diff --staged --quiet || (git commit -m "Automated Update 📈" && git push)
